groups:
- name: EcoFlow
  rules:
    - alert: EcoFlowOffline
      expr: ecoflow_online == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: EcoFlow is offline
        description: "Device {{ $labels.device }} has disappeared from the network"

    - alert: EcoFlowPowerOutage
      expr: ecoflow_inv_ac_in_vol == 0
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: EcoFlow detects power outage
        description: "Device {{ $labels.device }} detects power outage"

    - alert: EcoFlowLowRemainingTime
      expr: ecoflow_bms_ems_status_dsg_remain_time < 10
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: EcoFlow will discharge soon
        description: "Device {{ $labels.device }} will discharge in {{ $value }} min"

    - alert: EcoFlowHalfBattery
      expr: ecoflow_bms_bms_status_f32_show_soc < 50
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: EcoFlow half battery
        description: "Device {{ $labels.device }} battery level less than 50%"

    - alert: EcoFlowLowBattery
      expr: ecoflow_bms_bms_status_f32_show_soc < 10
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: EcoFlow low battery
        description: "Device {{ $labels.device }} battery level less than 10%"

    - alert: EcoFlowHighLoad
      expr: ecoflow_inv_output_watts > 1700 and ecoflow_inv_ac_in_vol == 0
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: EcoFlow high load
        description: "Device {{ $labels.device }} under high load: {{ $value }}W"
