# my global config
global:
  scrape_interval: 30s # Set the scrape interval to every 30 seconds. Default is every 1 minute.
  scrape_timeout: 15s
  evaluation_interval: 30s # Evaluate rules every 30 seconds. The default is every 1 minute.

#alerting:
#  alertmanagers:
#    - scheme: http
#      static_configs:
#        - targets:
#          - alertmanager:9093

rule_files:
  - 'alerts/*.yml'

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090

  - job_name: alertmanager
    static_configs:
      - targets:
        - alertmanager:9093

  - job_name: ecoflow
    static_configs:
      - targets:
          - ecoflow_exporter:9091
