version: "3.9"

# ------------------------------------------------------------
# PAKU IoT – UNIFIED STACK
#
# This compose file starts the full lightweight environment:
#   ruuvi-emulator → mosquitto → collector → postgres → grafana
#
# Start with: docker compose -f compose/stack.yaml up --build
# Stop with:  docker compose -f compose/stack.yaml down
#
# Each service has its own directory under stack/.
# ------------------------------------------------------------

services:
  # ------------------------------------------------------------
  # MOSQUITTO MQTT BROKER
  # Receives messages from the ruuvi-emulator.
  # The collector service will subscribe here.
  # ------------------------------------------------------------
  mosquitto:
    build: ../stack/mosquitto
    container_name: paku_mosquitto
    ports:
      - "1883:1883"
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-t", "$$SYS/#", "-C", "1", "-i", "healthcheck", "-W", "3"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s

  # ------------------------------------------------------------
  # POSTGRES – PERSISTENT STORAGE
  # Stores all sensor data.
  # The paku_pgdata volume ensures data persists across restarts.
  # ------------------------------------------------------------
  postgres:
    build: ../stack/postgres
    container_name: paku_postgres
    volumes:
      - paku_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U paku -d paku"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  # ------------------------------------------------------------
  # COLLECTOR
  # Reads MQTT messages from Mosquitto and writes them to Postgres.
  # Subscribes to paku/# and inserts measurements into the database.
  # ------------------------------------------------------------
  collector:
    build: ../stack/collector
    container_name: paku_collector
    depends_on:
      mosquitto:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      - MQTT_HOST=mosquitto
      - PGHOST=postgres
      - PGUSER=paku
      - PGPASSWORD=paku
      - PGDATABASE=paku

  # ------------------------------------------------------------
  # RUUVITAG EMULATOR
  # Sends fake sensor data to MQTT for testing.
  # Publishes RuuviTag-style JSON payloads to paku/ruuvi/van_inside.
  # ------------------------------------------------------------
  ruuvi-emulator:
    build: ../stack/ruuvi-emulator
    container_name: paku_ruuvi_emulator
    depends_on:
      mosquitto:
        condition: service_healthy
    environment:
      - MQTT_HOST=mosquitto
      - PUBLISH_INTERVAL=10
      - SENSOR_ID=van_inside

  # ------------------------------------------------------------
  # GRAFANA
  # Visualization layer that reads from Postgres.
  # The paku_grafana volume stores dashboards and Grafana state.
  # Access at http://localhost:3000 (no login required)
  # ------------------------------------------------------------
  grafana:
    build: ../stack/grafana
    container_name: paku_grafana
    volumes:
      - paku_grafana:/var/lib/grafana
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:3000/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
      
# ------------------------------------------------------------
# VOLUMES
# Centralized definitions for all persistent data directories.
# ------------------------------------------------------------
volumes:
  paku_pgdata:
  paku_grafana:
