# ------------------------------------------------------------
# PAKU IoT – UNIFIED STACK
#
# This compose file starts the full lightweight environment:
#   ruuvi-emulator + heater-emulator → mosquitto → collector → postgres → grafana
#
# Each service has its own directory under stack/.
# In this phase the goal is to run a clean end-to-end pipeline.
#
# Environment variables are loaded from .env file in same directory
# ------------------------------------------------------------

services:
  # ------------------------------------------------------------
  # MOSQUITTO MQTT BROKER
  # Receives messages from the Ruuvi emulator.
  # The collector service subscribes here.
  # ------------------------------------------------------------
  mosquitto:
    build:
      context: ../stack/mosquitto
      args:
        MQTT_USER: ${MQTT_USER:-paku}
        MQTT_PASSWORD: ${MQTT_PASSWORD:-paku}
        MQTT_CN: ${MQTT_CN:-mosquitto}
    container_name: paku_mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "8883:8883"
    volumes:
      - paku_mqttdata:/mosquitto/data

  # ------------------------------------------------------------
  # POSTGRES – PERSISTENT STORAGE
  # Stores all sensor data.
  # The paku_pgdata volume ensures data persists across restarts.
  # ------------------------------------------------------------
  postgres:
    build:
      context: ../stack/postgres
    container_name: paku_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - paku_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ------------------------------------------------------------
  # GRAFANA
  # Visualization layer that reads from Postgres.
  # The paku_grafana volume stores dashboards and Grafana state.
  # ------------------------------------------------------------
  grafana:
    build:
      context: ../stack/grafana
    container_name: paku_grafana
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "3000:3000"
    volumes:
      - paku_grafana:/var/lib/grafana

  # ------------------------------------------------------------
  # RUUVITAG EMULATOR
  # Sends fake sensor data to MQTT for testing.
  # Runs for 5 minutes then exits automatically.
  # Publishes to paku/ruuvi/van_inside every 5-10 seconds.
  # ------------------------------------------------------------
  ruuvi-emulator:
    build:
      context: ../stack/ruuvi-emulator
    container_name: paku_ruuvi_emulator
    restart: "no"
    depends_on:
      mosquitto:
        condition: service_started
    environment:
      MQTT_HOST: mosquitto
      MQTT_PORT: 1883
      MQTT_USER: ${MQTT_USER:-paku}
      MQTT_PASSWORD: ${MQTT_PASSWORD:-paku}
      MAX_RUNTIME_SECONDS: ${MAX_RUNTIME_SECONDS:-300}

  # ------------------------------------------------------------
  # HEATER EMULATOR
  # Simulates an Autoterm Flow 5D hydronic heater on MQTT.
  # Publishes state + telemetry, responds to start/stop commands.
  # Runs for MAX_RUNTIME_SECONDS then exits automatically.
  # ------------------------------------------------------------
  heater-emulator:
    build:
      context: ../stack/heater-emulator
    container_name: paku_heater_emulator
    restart: "no"
    depends_on:
      mosquitto:
        condition: service_started
    environment:
      MQTT_HOST: mosquitto
      MQTT_PORT: 1883
      MQTT_USER: ${MQTT_USER:-paku}
      MQTT_PASSWORD: ${MQTT_PASSWORD:-paku}
      DEVICE_ID: ${HEATER_DEVICE_ID:-emu01}
      MAX_RUNTIME_SECONDS: ${MAX_RUNTIME_SECONDS:-300}
      PUBLISH_INTERVAL: ${HEATER_PUBLISH_INTERVAL:-5}

  # ------------------------------------------------------------
  # COLLECTOR
  # Reads MQTT messages from Mosquitto and writes them to Postgres.
  # Subscribes to paku/ruuvi/van_inside and inserts data into the
  # measurements table.
  # ------------------------------------------------------------
  collector:
    build:
      context: ../stack/collector
    container_name: paku_collector
    restart: unless-stopped
    depends_on:
      mosquitto:
        condition: service_started
      postgres:
        condition: service_healthy
    environment:
      MQTT_HOST: mosquitto
      MQTT_PORT: 1883
      MQTT_USER: ${MQTT_USER:-paku}
      MQTT_PASSWORD: ${MQTT_PASSWORD:-paku}
      MQTT_TOPIC_PATTERN: "+/+/+/data"
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGDATABASE: ${POSTGRES_DB}

  # ------------------------------------------------------------
  # ECOFLOW COLLECTOR
  # Connects to EcoFlow Cloud API to collect power station data.
  # Requires ECOFLOW_ACCESS_KEY and ECOFLOW_SECRET_KEY in .env
  # ------------------------------------------------------------
  ecoflow-collector:
    build:
      context: ../stack/ecoflow-collector
    container_name: paku_ecoflow_collector
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ECOFLOW_ACCESS_KEY: ${ECOFLOW_ACCESS_KEY:-}
      ECOFLOW_SECRET_KEY: ${ECOFLOW_SECRET_KEY:-}
      ECOFLOW_DEVICE_SN: ${ECOFLOW_DEVICE_SN:-}
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGDATABASE: ${POSTGRES_DB}
      ECOFLOW_API_URL: ${ECOFLOW_API_URL:-https://api-e.ecoflow.com}
      REST_API_INTERVAL: ${REST_API_INTERVAL:-30}

  # ------------------------------------------------------------
  # OTA SERVICE
  # REST API for Over-The-Air firmware updates.
  # Provides endpoints for ESP devices to check/download updates
  # and admin APIs for firmware management and rollout control.
  # ------------------------------------------------------------
  ota-service:
    build:
      context: ../stack/ota-service
    container_name: paku_ota_service
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGDATABASE: ${POSTGRES_DB}
      FIRMWARE_STORAGE_PATH: /firmware
      API_KEY: ${OTA_API_KEY:-}
      PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - paku_firmware:/firmware

# ------------------------------------------------------------
# VOLUMES
# Centralized definitions for all persistent data directories.
# ------------------------------------------------------------
volumes:
  paku_pgdata:
  paku_grafana:
  paku_firmware:
  paku_mqttdata:
