# ------------------------------------------------------------
# PAKU IoT – PRODUCTION STACK
#
# Production-ready stack for deployment on a Hetzner VM.
# Based on the unified stack with production optimizations:
#   - Resource limits
#   - Restart policies
#   - Health checks
#   - Logging configuration
#
# Environment variables are loaded from .env file in same directory
# ------------------------------------------------------------

services:
  # ------------------------------------------------------------
  # MOSQUITTO MQTT BROKER
  # Receives messages from IoT devices.
  # The collector service subscribes here.
  # ------------------------------------------------------------
  mosquitto:
    build:
      context: ../stack/mosquitto
    container_name: paku_mosquitto
    restart: always
    ports:
      - "1883:1883"
    deploy:
      resources:
        limits:
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-t", "$$SYS/#", "-C", "1", "-W", "3"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # ------------------------------------------------------------
  # POSTGRES – PERSISTENT STORAGE
  # Stores all sensor data.
  # The paku_pgdata volume ensures data persists across restarts.
  # ------------------------------------------------------------
  postgres:
    build:
      context: ../stack/postgres
    container_name: paku_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-paku}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-paku}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - paku_pgdata:/home/paku/paku-data/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-paku} -d ${POSTGRES_DB:-paku}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # ------------------------------------------------------------
  # GRAFANA
  # Visualization layer that reads from Postgres.
  # The paku_grafana volume stores dashboards and Grafana state.
  # ------------------------------------------------------------
  grafana:
    build:
      context: ../stack/grafana
    container_name: paku_grafana
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_SERVER_ROOT_URL: ${GF_SERVER_ROOT_URL:-http://localhost:3000}
      POSTGRES_USER: ${POSTGRES_USER:-paku}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-paku}
    ports:
      - "3000:3000"
    volumes:
      - paku_grafana:/home/paku/paku-data/grafana
    deploy:
      resources:
        limits:
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # ------------------------------------------------------------
  # RUUVITAG EMULATOR
  # Sends fake sensor data to MQTT for testing.
  # NOTE: In production, you may want to disable this and use
  # real IoT devices instead.
  # Publishes to paku/ruuvi/van_inside every 5-10 seconds.
  # ------------------------------------------------------------
  ruuvi-emulator:
    build:
      context: ../stack/ruuvi-emulator
    container_name: paku_ruuvi_emulator
    restart: always
    depends_on:
      mosquitto:
        condition: service_healthy
    environment:
      MQTT_HOST: mosquitto
      MQTT_PORT: 1883
    deploy:
      resources:
        limits:
          memory: 64M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # ------------------------------------------------------------
  # COLLECTOR
  # Reads MQTT messages from Mosquitto and writes them to Postgres.
  # Subscribes to paku/ruuvi/van_inside and inserts data into the
  # measurements table.
  # ------------------------------------------------------------
  collector:
    build:
      context: ../stack/collector
    container_name: paku_collector
    restart: always
    depends_on:
      mosquitto:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      MQTT_HOST: mosquitto
      MQTT_PORT: 1883
      MQTT_TOPIC: paku/ruuvi/van_inside
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: ${POSTGRES_USER:-paku}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGDATABASE: ${POSTGRES_DB:-paku}
    deploy:
      resources:
        limits:
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# ------------------------------------------------------------
# VOLUMES
# Centralized definitions for all persistent data directories.
# ------------------------------------------------------------
volumes:
  paku_pgdata:
  paku_grafana:
